abbr -a -- d docker 
abbr -a -- db 'docker build -t test:latest .' 
abbr -a -- dc docker-compose 
abbr -a -- dcu 'docker-compose up -d' 
abbr -a -- di 'docker image' 
abbr -a -- dp 'docker ps' 
abbr -a -- dr 'docker run -d' 
abbr -a -- dsh 'docker container exec -it bash' 
abbr -a -- dtidy 'docker container rm (docker container ls -aq) -f'
abbr -a -- g git 
abbr -a -- ga 'git add . -v' 
abbr -a -- gb 'git branch' 
abbr -a -- gbl 'git blame' 
abbr -a -- gc 'git commit -m' 
abbr -a -- gca 'git commit --amend -m' 
abbr -a -- gch 'git checkout' 
abbr -a -- gcp 'git cherry-pick' 
abbr -a -- gd 'git diff' 
abbr -a -- gf 'git fetch' 
abbr -a -- gl 'git logg' 
abbr -a -- gm 'git merge' 
abbr -a -- gp 'git push' 
abbr -a -- gpf 'git push --force-with-lease' 
abbr -a -- gpl 'git pull' 
abbr -a -- gr 'git remote' 
abbr -a -- grb 'git rebase' 
abbr -a -- gs 'git status' 
abbr -a -- gst 'git stash' 
abbr -a -- h helm 
abbr -a -- hu 'helm uninstall' 
abbr -a -- k kubectl 
abbr -a -- kd 'kubectl describe' 
abbr -a -- kdd 'kubectl describe deploy' 
abbr -a -- kgdg 'kubectl get deployments | grep' 
abbr -a -- kgpg 'kubectl get pods | grep' 
abbr -a -- kl 'kubectl logs' 
abbr -a -- kld 'kubectl logs --selector app=' 
abbr -a -- kp 'kubectl port-forward' 
abbr -a -- kpk 'kubectl port-forward 9092:9092' 
abbr -a -- kpm 'kubectl port-forward 27018:27017' 
abbr -a -- kpw 'kubectl port-forward 8080:8080' 
abbr -a -- kpz 'kubectl port-forward 2181:2181' 
abbr -a -- ks 'kubectl scale deployment --replicas=0' 
abbr -a -- ksh 'kubectl exec --stdin --tty  -- /bin/bash' 
abbr -a -- kx kubectx 
abbr -a -- l 'ls -lah'
abbr -a -- n npm 
abbr -a -- ni 'npm install'
abbr -a -- nrb 'npm run build' 
abbr -a -- nrl 'npm run lint' 
abbr -a -- nrp 'npm run prettier' 
abbr -a -- nrt 'npm run test' 
abbr -a -- nrtc 'npm run test -- --coverage'
abbr -a -- nrtw 'npm run test -- --watch'
abbr -a -- ns 'npm start' 
abbr -a -- nu 'npm uninstall'
abbr -a -- ssha 'ssh-add ~/.ssh/id_rsa' 

